remove.packages(c("ggplot2", "data.table"))
install.packages('Rcpp', dependencies = TRUE)
install.packages('ggplot2', dependencies = TRUE)
install.packages('data.table', dependencies = TRUE)
install.packages("shiny")
install.packages("bootstrap")
install.packages("jpeg")
install.packages("DT")
install.packages("gsubfn")
install.packages("proto")
install.packages("sqldf")
install.packages("plyr")
install.packages("shinyjs")
install.packages("shinyBS")
install.packages("shinydashboard")
install.packages("plotly")
install.packages("googleVis")
install.packages("lubridate")